### ISSUE TITLE
Best way to get global errors

### ISSUE THREAD

**Issue by eduardodallmann** [seasonedcc/remix-forms#139]
I'm applying 'remix-forms' to an existing remix project.
Currently we show a toast for successes and errors resulting from the form.
Is there any good way to catch all errors or just the first one and pass them in return?

```
export const action: ActionFunction = async ({
  request,
}): Promise<TypedResponse<MyActionReturn>> => {
  const mutation = makeDomainFunction(schema)(async (values) => {
    throw new Error('very bad');

    return update(values);
  });

  const result = await performMutation({ request, schema, mutation });

  if (!result.success) {
    console.error('This errro:', result.errors, 'on try sent:', result.values);
    return json(
      {
        ...result,
        message: result.errors._global?.join(', ') || 'Any error', //<--------- HERE
      },
      400,
    );
  }

  return json({ message: 'save!' });
};
```

I understand that it's not a good practice to access properties with an underscore, even the lint is complaining. This is also not pretty: `result.errors._global?.[0]`

Thanks for any help. And thanks for the lib, it's really good.

**Comment by gustavoguichard** [comment]
Hey @eduardodallmann ! Thank you for the feedback!

I think your approach looks good but also take a look at [mapError](https://github.com/SeasonedSoftware/domain-functions#maperror) it can be used in your domain-function compositions to achieve that.
