### ISSUE TITLE
[question] any plans to have this lib also as a sveltekit package?

### ISSUE THREAD

**Issue by FranciscoKloganB** [seasonedcc/remix-forms#147]
Pure curiosity.

I've enjoyed learning Remix a lot, but I kind of need a break from React. Just feels old to me I am afraid. I was looking into learning Svelte/SvelteKit (1.0 already released) or Solid.JS/SolidStart (beta). The thing is... Porting my little side project involves losing `seasonedcc/remix-forms`. Yes, I like this lib so much, I just can't find the courage to try out the other frameworks/meta-frameworks! :dancers: 

So, I just went ahead and asked if you are not secretly working on something like this.

**Comment by gustavoguichard** [comment]
Hey @FranciscoKloganB ! Nice to hear you like RF so much!

AFAICT it will only run where react-router runs, which currently means react and soon preact.

Even if Remix start supporting other view libraries like solid or svelte it would still require a lot of work in this repo though. So probably not in the foreseeable future.

**Comment by FranciscoKloganB** [comment]
Thank you for the straight response! :)
