### ISSUE TITLE
Support the other React Hook Form validators?

### ISSUE THREAD

**Issue by CSFlorin** [seasonedcc/remix-forms#149]
React Hook Form has more resolvers than just for zod: https://github.com/react-hook-form/resolvers It would be nice to not require zod when this library is meant to support anything RHF does.

**Comment by gustavoguichard** [comment]
> when this library is meant to support anything RHF does

I don't think that is a valid statement. This library relies heavily on Zod as much as RHF.

I don't see that happening anytime soon. There are requests to use it with other frameworks such as Svelte, Solid.. if we ever end up extracting some lower level primitives from RF we might be able to get to that point.

Anyway I wouldn't count on that for short/mid-term.

**Comment by CSFlorin** [comment]
Ah ok I thought I had read or heard that you are meant to be able to eject to RHF anytime. No worries
