### ISSUE TITLE
Abstracting Required Indicator

### ISSUE THREAD

**Issue by joshmedeski** [seasonedcc/remix-forms#167]
Thanks for the package! I enjoy using it so far.

How can I abstract this type of logic so it happens by default on all fields?

https://remix-forms.seasoned.cc/examples/render-field/required-indicator

If I did this manually for all my fields I'd end up with hundreds of extra lines of code. I'd love to keep this DRY if possible. I'm noticing the default `label` component has no context to the input. Perhaps updating the package to automatically support passing input context into the default label component?

I'm willing to make a PR if you can suggest a strategy.

**Comment by danielweinmann** [comment]
Hey, @joshmedeski!

The goal of renderField is for you to use it on your [custom form component](https://remix-forms.seasoned.cc/get-started). That way, you'll abstract the required indicator for all fields on all forms that render your custom form.

But we also have the [useField hook](https://remix-forms.seasoned.cc/examples/forms/use-field), where you can access the field context inside your label component.

I'm closing the issue for now but feel free to reopen it at any time :)

**Comment by joshmedeski** [comment]
Thanks @danielweinmann, the useField hook worked perfectly!
