### ISSUE TITLE
Access session cookie in mutation

### ISSUE THREAD

**Issue by johnslipper** [seasonedcc/remix-forms#176]
Hi there, loving the library and the ease of dealing with fullstack validation! Thanks you for the great work.

I have a question: I am trying to get access to the request within the mutation function returned by the `makeDomainFunction` to be able to access a session cookie token. Is this possible? 

Potentially I'm going about it the wrong way, but currently all app data queries/mutations go via `/api` resource routes that proxy an external API. When I post the form to the action function of the page it does the API work there using the request token. Haven't been able to do the same with Remix Forms so far.

**Comment by gustavoguichard** [comment]
Hi @johnslipper , thank you for the feedback!

Have you tried using [`performMutation`](https://remix-forms.seasoned.cc/examples/actions/custom-response) yet?

**Comment by danielweinmann** [comment]
Hey, @johnslipper! Thank you!

[Domain Functions](https://github.com/seasonedcc/domain-functions) was designed _not_ to receive requests and other "controller stuff." Instead, we do the "controller" work inside the actions and loaders and pass the relevant data as input or [environment](https://github.com/seasonedcc/domain-functions#taking-parameters-that-are-not-user-input) to the domain function. In your example, you could have a helper function that extracts the request token inside your action and [passes it to the mutation as part of the environment](https://remix-forms.seasoned.cc/examples/actions/environment).

You could theoretically pass the request using Zod's [instanceof](https://zod.dev/?id=instanceof) and add it to the mutation's schema. But I don't recommend doing that. Decoupling your business logic from your framework is the goal of Domain Functions and makes your life much easier in the long term.

Is that too much of a departure from your current approach?

**Comment by gustavoguichard** [comment]
Cool @danielweinmann , I just realized I completely missread John's question 😅

**Comment by johnslipper** [comment]
Thank you @danielweinmann. I have successfully used the [environment](https://github.com/seasonedcc/domain-functions#taking-parameters-that-are-not-user-input) to pass in the required data and make the API call.
