### ISSUE TITLE
Suport Remix's `v2_normalizeFormMethod`

### ISSUE THREAD

**Issue by danielweinmann** [seasonedcc/remix-forms#178]
https://remix.run/docs/en/main/pages/v2#formmethod

I prefer to make Remix Forms infer which Remix version we're using and adjust accordingly. But if that turns out to be too hard, I'm reluctantly open to making a breaking change.

Thanks, @arjunyel, for bringing this to our attention via #177.

**Comment by meza** [comment]
This is probably related.

Wanted to use the library for a project but am running into this now. I guess I'll have to wait until this gets figured out

![image](https://user-images.githubusercontent.com/211977/230723746-1ac14d8f-871d-4a62-ab9a-e95bf4a11f6b.png)

**Comment by arjunyel** [comment]
@meza you can use ts-ignore or patch-package for now

**Comment by danielweinmann** [comment]
@arjunyel @meza, [v1.6.3](https://github.com/seasonedcc/remix-forms/releases/tag/v1.6.3) is out and fixes this 💪🏽 thank you for the contribution!
