### ISSUE TITLE
Global error duplicate with multiple forms

### ISSUE THREAD

**Issue by luizluchete** [seasonedcc/remix-forms#195]
Hello, first thanks for this lib, it has helped me a lot in my projects.

when I have 2 forms in the same route using remix-forms, if one of them returns "throw", the global error is shown in the 2 forms, correct?
It would be possible to filter the global error of the current form to list only in it.

I created an example with the "multiple forms" documentation code, I changed it only to return a "throw" and the error appears in the 2 forms.
```typescript

import { ActionFunction } from '@remix-run/node'
import { makeDomainFunction } from 'domain-functions'
import { z } from 'zod'
import { Form, formAction } from '~/remix-forms'

const loginSchema = z.object({
  _action: z.literal('/login'),
  email: z.string().email(),
  password: z.string().min(8),
})

const contactSchema = z.object({
  _action: z.literal('/contact'),
  email: z.string().email(),
  message: z.string().min(1),
})

const loginMutation = makeDomainFunction(loginSchema)(async (values) => {
  throw 'Deu Ruim'
})

const contactMutation = makeDomainFunction(contactSchema)(
  async (values) => values
)

export const action: ActionFunction = async ({ request }) => {
  const formData = await request.clone().formData()
  const action = formData.get('_action')

  if (action === '/login') {
    return formAction({
      request,
      mutation: loginMutation,
      schema: loginSchema,
    })
  }

  if (action === '/contact') {
    return formAction({
      request,
      mutation: contactMutation,
      schema: contactSchema,
    })
  }
}

export default () => {
  return (
    <>
      <Form
        schema={loginSchema}
        buttonLabel="Login"
        hiddenFields={['_action']}
        values={{ _action: '/login' }}
      />
      <Form
        schema={contactSchema}
        multiline={['message']}
        buttonLabel="Contact Us"
        hiddenFields={['_action']}
        values={{ _action: '/contact' }}
      />
    </>
  )
}

```
![Capturar](https://user-images.githubusercontent.com/57816456/234407656-3f2045da-d751-4346-9508-1659caaa02fe.PNG)

Sorry for the bad english, I still use google translator

**Comment by danielweinmann** [comment]
Hey, @luizluchete! Thanks for reporting this issue. There is no way to do this right now out of the box. However, I believe that if you use one [fetcher](https://remix-forms.seasoned.cc/examples/forms/use-fetcher) for each form your example will work. Can you test it and let us know?

I'll leave the issue open until we decide how we'll address it.

Thank you again!

**Comment by luizluchete** [comment]
Thanks @danielweinmann 

I added the "fetcher" for forms and it solved the problem.
