### ISSUE TITLE
Custom Component typings

### ISSUE THREAD

**Issue by ReptoxX** [seasonedcc/remix-forms#212]
Hello,

i'm not sure if this is already mentioned (searched through the issues):
I use a custom Button component with additional props (like: size, variant, block).
When using the `<Button>` i can pass them in, it works but gives me an ugly typescript error.

```tsx
{({ Field, Button, Errors, register }) => (
  <FormContainer size="md">
    <Errors className="mb-8" />
    <Field name="userName" />
    <Field name="password">
    {({ Label, Errors }) => (
      <>
        <Label />
        <PasswordInput {...register('password')} />
        <Errors />
      </>
    )}
    </Field>
    <Field name="rememberMe" />
    <Button block />
    //      ^ -- throws: Property 'block' does not exist on type 'IntrinsicAttributes & ClassAttributes<HTMLButtonElement> & ButtonHTMLAttributes<HTMLButtonElement>'
    <div className="mt-4 text-center">
      <span>Don't have an account yet? </span>
    </div>
  </FormContainer>
)}
```

Is there a way of changing the type of the button throughout the project?

Best Regards

**Comment by danielweinmann** [comment]
Hey, @ReptoxX! We're figuring out how to do this, but it will likely be a v2 API if we find a good solution. We're keeping track of the discussion on #121 (which I couldn't help but notice it's a mirror of #212 😅 ).

We appreciate any contributions! Thank you.

**Comment by ReptoxX** [comment]
Thanks for the friendly answer, i must've missed the issue.
