### ISSUE TITLE
Multiple Checkboxes

### ISSUE THREAD

**Issue by josekenya** [seasonedcc/remix-forms#216]
Hi, how do i go about rendering multiple checkboxes?

**Comment by danielweinmann** [comment]
Hey, @josekenya! Do you mean one field with multiple options or multiple boolean fields?

Multiple boolean fields are straightforward: add them to the schema, and they will be rendered as checkboxes.

One field with multiple options is more complex, and we don't have a native solution. But you can achieve the result you want by following our [array of strings](https://remix-forms.seasoned.cc/examples/schemas/array-of-strings) example and adapting it to use an array of booleans with checkboxes.

Did I understand you correctly?

**Comment by josekenya** [comment]
Hi, I appreciate the response. My issue particularly was one field with multiple string value options.

**Comment by danielweinmann** [comment]
Then it's pretty similar to the array of strings example, just changing the UI. Can you try it and let us know if it worked?

I'm closing the issue but feel free to reopen it at any time.
