### ISSUE TITLE
Handle `z.object`

### ISSUE THREAD

**Issue by hauptrolle** [seasonedcc/remix-forms#231]
Hey,

I really want to use `remix-forms` in our application, but I can't find an example how to use `z.object` for nested fields.
For example:
```ts
const schema = z.object({
  // Basic Settings
  fromDisplayName: z.string().min(1),
  replyToDisplayName: z.string().min(1),
  replyTo: z.string().min(1).email(),

  // Custom Settings
  customSettings: z
    .object({
      from: z.string().min(1).email(),
    })
    .optional(),
});
```

I've found some related issues but no solution so far 😞

**Comment by danielweinmann** [comment]
Hey, @hauptrolle! We haven't found the right abstraction for an out-of-the-box solution yet, but you can achieve that by managing react-hook-form's state manually and adding hidden inputs with `customSettings[from]`, and so on, as their name.

Something similar to what we do with the [array of objects example](https://remix-forms.seasoned.cc/examples/schemas/array-of-objects), but skipping the array part.
