### ISSUE TITLE
Remix forms site example no longer maintained?

### ISSUE THREAD

**Issue by Jarrodsz** [seasonedcc/remix-forms#235]
Shame the 
https://github.com/seasonedcc/remix-forms-site

is no longer maintainted, it seemed like the good start point to switch from chakra-ui to tailwind and have 
a foundation to not implement all myself.

I upgraded the repro to remix v2.

Is there another place to look for a full implementation of tailwind with remix-forms?
OR would this repro still be the best reference.

Sorry for posting here but the other repro is archived and could no longer comment.

**Comment by danielweinmann** [comment]
Hey, @Jarrodsz! The website now lives in the same monorepo as the package. Here it is: https://github.com/seasonedcc/remix-forms/tree/main/apps/web
