### ISSUE TITLE
domain-functions deprecated, are you planing to update remix-forms docs

### ISSUE THREAD

**Issue by povilasDadelo** [seasonedcc/remix-forms#245]
Found that domain-functions lib (which is mentioned it Get started guide) is deprecated.

Are you planing to update docs/examples?

**Comment by gustavoguichard** [comment]
Hi @povilasDadelo !
domain-functions has evolved and changed its name to composable-functions. Remix-forms is probably gonna get a nice update soon but it should work without problems with domain-functions@3 which we are maintaining.

**Comment by povilasDadelo** [comment]
Thanks!
