### ISSUE TITLE
defaultValues

### ISSUE THREAD

**Issue by grischad** [seasonedcc/remix-forms#247]
Greetings, how could I populate a form with defaultValues from localStorage? So far all I tried resulted in an empty form.

**Comment by gustavoguichard** [comment]
Have you tried the `values` prop of the form?
To get the values from localStorage I'd use a `clientLoader` and then pass those values through `values` ;)

**Comment by grischad** [comment]
Dear Gustavo, thanks for your reply, it works! :)
I had tried values prop before but not the clientLoader and now it's charmingly populating the form, ouff. 
All the best to you!

**Comment by gustavoguichard** [comment]
@grischad I'm glad to hear that!!
