### ISSUE TITLE
Add option to reset form on or after submit

### ISSUE THREAD

**Issue by danielweinmann** [seasonedcc/remix-forms#69]
Requested by @zolzaya on #68. I think this is a good helper.

Maybe we can have the option of doing it optimistically or pessimistically. Something like `resetOnSubmit?: boolean` and `resetAfterSubmit?: boolean`.

**Comment by felipefreitag** [comment]
I talked to @diogob and adding multiple boolean options doesn't seem simple to maintain or extend.

I think we should also consider that the [reset function](https://react-hook-form.com/api/useform/reset) has plenty of optional parameters and it's possible this will bring up further use cases down the road.

How about having an option like `resetMode`: `[none, onSubmit, afterSubmit]`?

**Comment by diogob** [comment]
How about just using the [current approach suggested](https://github.com/SeasonedSoftware/remix-forms/issues/68#issuecomment-1199124007) by @gustavoguichard but provide composable helpers so the user can just say:

```ts
<Form
  schema={schema}
  fetcher={fetcher}
  onTransition={resetAfterSubmit()}
>
```

**Comment by felipefreitag** [comment]
Not sure how that would work with other possible uses of `onTransition`, but it seems an interesting API

**Comment by hauptrolle** [comment]
Any updates here? Looks like the `onTransition` prop does not receive the `transition` anymore ... :(

**Comment by danielweinmann** [comment]
> Any updates here? Looks like the `onTransition` prop does not receive the `transition` anymore ... :(
> 
> Should we use the `useNavigation` hook from remix and do something like this?
> 
> ```
> const { state, formMethod } = useNavigation();
> 
> return (
>       <Form
>         schema={schema}
>         onTransition={({ reset }) => {
>           if (state === "loading" && formMethod !== "GET") {
>             reset();
>           }
>         }}
>       />
> )
> ```

Yes, exactly that! And if you're using a fetcher you'll get the state, formMethod, etc, from it ;)

**Comment by danielweinmann** [comment]
I'm closing this issue for now because we do not intend to add an API for that. We believe the current API is sufficient for now.
